### ISSUE TITLE
For Poisson solve, output is showing electric potential for all 4 components. Last three components should be magnetic potential (0 for no B field case)

### ISSUE THREAD

**Issue by crskolar** [ammarhakim/gkyl#149]
I'm running sims with this field solver in the input file: 
```
   -- Field solver.
   field = Plasma.Field {
      epsilon0 = epsilon_0, mu0 = mu_0,
      evolve   = true, -- Evolve field?
      hasMagneticField = false,
      bcLowerPhi = {{T="D", V=V_left}},
      bcUpperPhi = {{T="D", V=0.0}},
   },
```
This should output a 4 component output with phi and 3 components of 0s (since no B field being included). However, all the outputs are the electric potential.

**Comment by manauref** [comment]
@crskolar, it's an electrostatic simulation without external B. Why should it output a (zero) vector potential?

**Comment by JunoRavin** [comment]
The output in field is (phi_ext, A_ext) always no? It's just the last 3 are zero in a pure Poisson calculation

**Comment by manauref** [comment]
@crskolar I think you are in an older version of the code
please pull the latest in gkylzero and gkyl/g0-merge and build again, preferably from scratch. If this fixes it please close the issue.

**Comment by crskolar** [comment]
@manauref You were correct. g0 and g0-merge branch fixes it. I'll work with Kolter to get the emissionBC branches all merged in so that I don't keep having these issues. 

I'm gonna close this issue now.
