### ISSUE TITLE
Separate primMom kernels into separate files by polyOrder

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkyl#16]
Also remove p=2 primMom kernels for 3x3v.

This will make the build easier/faster on some systems.

**Comment by nmandell** [comment]
Since we might be doing a lot of rebuilding of the code during the hackathon, it might be helpful to have this re-organization done before then. Otherwise we might spend a lot of time waiting for large kernels to build.

**Comment by ammarhakim** [comment]
Yes, we need to regenerate a bunch of kernels. However, before we do this it is best to discuss the mechanism and naming schemes etc so we have a uniform way to do this.

**Comment by nmandell** [comment]
The GK kernels and binOp are already separated and so I think it would be best to match the way it is done in those.
