### ISSUE TITLE
useShared = true lacks error catching for when decompCuts =/= number of nodes

### ISSUE THREAD

**Issue by JunoRavin** [ammarhakim/gkyl#17]
When running with useShared = true, if the decompCuts does not equal the number of nodes, one still obtains the error that:

ERROR: CartProdDecomp: Number of sub-domains and processors must match

but the simulation does not time out and will still keep running. Likely due to issue that shared communicator thinks it's still valid and tries to share memory across compute nodes. 

Error present as of commit c15e2df on March 31st. Likely still present as shared memory has had issues lately. Need a lot more testing of shared memory.

**Comment by ammarhakim** [comment]
We need regression tests in parallel so all these errors can be tested. I will work on this as soon as the RDG bug is found.

**Comment by JunoRavin** [comment]
I agree. I would also like to come up with a set of more extensive unit tests for useShared=true. I did not even think to test this since, when useShared = false, the simulations do exit when decompCuts is not equal to the number of MPI processes specified. Some brainstorming for edge cases/user silliness (as just happened with me) is definitely required.
