### ISSUE TITLE
"Moments" app doesn't seem to exist

### ISSUE THREAD

**Issue by skylord-a52** [ammarhakim/gkyl#172]
My setup is able to run VlasovMaxwell and Gyrokinetic apps just fine.

However, trying to run any of the given example scripts for Euler/Ten-moment sims gives the following error:

```bash
> gkyl rt-10m-gem.lua
*** LOAD ERROR ***
 [string "-- Gkyl -------------------------------------..."]:2: attempt to call field 'Moments' (a nil value)
```

I set up this small test script.
```lua
local Apps = require("App.PlasmaOnCartGrid")

for key,value in pairs(Apps) do
    print(key, value)
end
```
Running it through gkyl gives the following:

```bash
> gkyl test.lua
Gyrokinetic     function: 0x7fe173393770
VlasovMaxwell   function: 0x7fe1733937e0
```

There's no entry for a Moment app! Somehow, my version of Gkeyll only has VlasovMaxwell and Gyrokinetic apps available. Redownloading and rebuilding Gkeyll didn't help.

**Comment by JunoRavin** [comment]
<img width="844" alt="Screenshot 2024-03-16 at 9 09 30 PM" src="https://github.com/ammarhakim/gkyl/assets/7997308/376bb3ed-1edc-410f-961f-e1568c72a970">

Please see this note in the Gkeyll documentation. If you are running things through G2 you have to switch to the pre-g0 branch. The updated fluid solver should be back into G2 using the gkylzero library directly in the next few months, but you can use the older fluid solver in the pre-g0 branch. 

You can also run the fluid solver directly through the gkylzero library if you are comfortable with just running C input files directly (https://github.com/ammarhakim/gkylzero). We are working on re-integrating the Fluid solver functionality from the improvements of the gkylzero library but just haven't completed the Lua-C wrapping.

**Comment by skylord-a52** [comment]
Ah, my bad, I missed that! Thank you.
