### ISSUE TITLE
GPU thoughts about structuring updaters (DistFuncMomentCalc as an example)

### ISSUE THREAD

**Issue by nmandell** [ammarhakim/gkyl#18]
The primary point here is that we need a way to pass function pointers into `__global__` CUDA kernels. these function pointers will point to particular existing kernels (instrumented with `__host__ __device__` CUDA preprocessors). this way we can have generic `__global__` kernels that do loops over cells, and then in each cell we can call a particular kernel function.

The DistFuncMomentCalc updater is the furthest along on GPU implementation, and should be used as a template in many regards. Credit to @manauref. So I will use this as an example for what I mean. I'm going to go through the currently implemented DistFuncMomentCalc workflow step by step and then make some comments. 

Here is the CUDA-relevant block in `Updater/DistFuncMomentCalc.lua` where things start:
```
   if GKYL_HAVE_CUDA and self.calcOnDevice then
      local d_PhaseGrid  = grid:copyHostToDevice()
      local d_PhaseRange = Range.copyHostToDevice(phaseRange)

      local deviceNumber     = cudaRunTime.GetDevice()
      local deviceProps, err = cudaRunTime.GetDeviceProperties(deviceNumber)

      local phaseRangeDecomp = LinearDecomp.LinearDecompRange {
         range = phaseRange:selectFirst(pDim), numSplit = grid:numSharedProcs() }
      local numCellsLocal = phaseRange:selectFirst(pDim):volume()

      local numThreads = GKYL_DEFAULT_NUM_THREADS
      local numBlocks  = math.floor(numCellsLocal/numThreads)+1

      self._momCalcFun(d_PhaseGrid, d_PhaseRange, deviceProps, numBlocks, numThreads, distf:deviceDataPointer(), mom1:deviceDataPointer())

      cudaRunTime.Free(d_PhaseRange)
   else
      .... regular code ....
```
The C function that is pointed to by `self._momCalcFun` is `cuda_MomentCalc1x1vSer_M0_P1`. It lives in `Updater/momentCalcData/DistFuncMomentCalcSer1x1vDevice.cu`. This is a C function that wraps a CUDA kernel call:
```
// C function that wraps call to moment calculation global CUDA kernel
void cuda_MomentCalc1x1vSer_M0_P1(RectCart_t *grid, Range_t *range, GkDeviceProp *prop, int numBlocks, int numThreads, const double *fIn, double *out) {

  int warpSize = prop->warpSize;

  d_calcMom1x1vSer_M0_P1<<<numBlocks, numThreads, 2*(numThreads/warpSize)*sizeof(double)>>>(grid, range, fIn, out);
}
``` 
The global CUDA  kernel `d_calcMom1x1vSer_M0_P1` also lives in `Updater/momentCalcData/DistFuncMomentCalcSer1x1vDevice.cu`. It threads over cells, as we have discussed before. Each thread is responsible for a cell, and it calls `MomentCalc1x1vSer_M0_P1`. This is one of the typical maxima-generated C kernels that we know and love, except that it has been instrumented with `__host__ __device` preprocessors to allow it to be called from within this `__global__` CUDA kernel.

This workflow works. However, as is it would require separate reduction kernels and wrapper kernels for every moment, dimensionality, polynomial order, etc. So this is where we need to do a bit more work to generalize these functions so that they can be reused. (I'm sure that Mana has thought about these things already, but just wanted to write up a full example.) 

I think the global kernel which calls the local kernel and does the reduction should be generic so that it can be used for any moment, dimensionality, polynomial order, etc. Such a generic kernel would then need some way to know what local kernel function to call (in this case `MomentCalc1x1vSer_M0_P1`). Perhaps templating is the way to go for this, but I'm not sure if CUDA kernels can be templated. In any case, I'm thinking about something like this:
- The lua function pointer `self._momCalcFun` could point to a wrapper to some generic moment reduction kernel, something like
```
// C function that wraps call to moment calculation global CUDA reduction kernel
void cuda_calcMoment_wrapper(RectCart_t *grid, Range_t *range, GkDeviceProp *prop, int cdim, int pdim, function_pointer, int numBlocks, int numThreads, const double *fIn, double *out) {

  int warpSize = prop->warpSize;

  cuda_calcMoment<<<numBlocks, numThreads, 2*(numThreads/warpSize)*sizeof(double)>>>(grid, range, cdim, pdim, function_pointer, fIn, out);
}
``` 
where we now are directly passing `cdim` and `pdim`, and also a pointer to a moment calculator kernel function `function_pointer`, which in this specific case would point to `MomentCalc1x1vSer_M0_P1`. 
- The global kernel `__global__ cuda_CalcMoment` will be more or less the same as what Mana has in `d_calcMom1x1vSer_M0_P1`, except for the hard-coded dimensional parameters will be replaced with parameters related to `cdim` and `pdim`, and the local kernel function (currently hard-coded to be `MomentCalc1x1vSer_M0_P1`) will be taken from the `function_pointer` argument. This will allow this global kernel to be reused for every moment, dimensionality, polynomial order, etc.

This structure will be similar for other updaters, where we will want to have a generic looping kernel, into which we pass dimensionality, polynomial order, etc, and also a function pointer to the particular local kernel function (our maxima-generated kernels) that should be called. We just need to figure out the architecture for passing function pointers into kernels.

**Comment by ammarhakim** [comment]
Can't we simply call the functions rather than work with function pointers? I mean, if we have a based templated Eq class then the template specializations could provide the wrappers to the various kernels.

I suggest we discuss this on Tuesday. Clearly, this is the most important thing to figure out. I have coded up an example Eq object and Updater that illustrates the idea of template policies which I can show then. Not tested on device but the basis idea seems to work on the host.

**Comment by nmandell** [comment]
this might be helpful: https://leimao.github.io/blog/Pass-Function-Pointers-to-Kernels-CUDA/

**Comment by ammarhakim** [comment]
This specific Updater example is very useful. Thanks to @manauref & @nmandell  for making this and thinking about this. It allows us to look at a very specific example and plan an abstraction that automates a lot of this grunge work. 

To bring everyone up to speed please explain in detail the sequence of calls when we meet on Tuesday.

An example of abstraction: I would prefer not to have these if statements all over the place in Updaters to choose between CUDA and regular code. We can automate and abstract this out by letting the base class of Updater decide if we are on a device and call some specific methods (like setting up various kernels etc). So then the Updater methods would be cleaner: one set for cuda and other CPUs, and the choice made in the guts of the code and not in each and every object.

How to do all this is not clear to me yet, though I am sure we can come up with a very elegant and natural solution which will **not** need messy if blocks like this, allowing for more flexible and extensible code. My plan is to fully and throughly understand the calling issues the coming week, and then before June 8th work out a powerful abstraction to make all this as natural as possible.

This is an excellent start!

**Comment by nmandell** [comment]
Do you mean having something like a separate _advanceOnDevice method for each updater?

**Comment by ammarhakim** [comment]
Yes, something like that. Also initCuda() method for each updater. Then the base updater object detects if we are using a device and calls the appropriate method. That way, if an updater does not have a CUDA implementation it runs on the host and copies the data to the device if needed. So the whole system would be totally transparent (though not efficient) and allow us to run and move things incrementally.
