### ISSUE TITLE
1x2v p2 GkLBO kernels don't appear to conserve energy

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkyl#20]
This issue apparently arose when we switched from global LF fluxes, to local, quadrature point-based LF fluxes.

**Comment by JunoRavin** [comment]
The quadrature point based local lax friedrichs fluxes are only being used for the drag term correct? And for both v_parallel and mu?

**Comment by manauref** [comment]
Correct.

**Comment by manauref** [comment]
This had to do with the way we were converting from nodal to modal, and the fact that there isn't an exact quadrature rule for p=2 the way there is for p=1 (because p=1 is a tensor product basis).

Since then we've change the way this is done, and do get p=2 energy conservation now.
