### ISSUE TITLE
test6 in CartField unit test

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkyl#24]
I disabled test6 in Unit/test_CartFieldCuda.lua because it was throwing an error in Portal (see below). Perhaps this is not an issue and I'm running the test the wrong way. If that's the case, can the author enlighten me?

Also, this unit test prints out a bunch of indices. Is this left over from some dev or debug work? should it be removed?

**Comment by manauref** [comment]
**Jimmy:** 
test_6 probably does not work on Portal because Portal does not have a CUDA-aware MPI. I’m not sure that’s worth disabling it

This does raise a question of whether the unit tests should assume something about the MPI the code is built with, since it took effort to get these things to work on Adroit and Traverse. Do we care about a unit test failing on a GPU machine with no CUDA-aware MPI?

**Mana:**
In this case there should be a flag that disables that test, because for example, suppose someone else adds a new test, test_7, after the cuda-aware MPI test. Since test_6 seg faults, test_7 would not run.

**Comment by JunoRavin** [comment]
Hmm, yes if you do not have CUDA-aware MPI this test will seg-fault because MPI_Send/Recv do not know what a device pointer is. I do not know off the top of my head what the flag should be. I am not sure how easily one can detect if the MPI being employed is CUDA-aware.

**Comment by ammarhakim** [comment]
I believe one can use the following function to check if there is such support. See:

https://www.open-mpi.org/doc/v2.1/man3/MPIX_Query_cuda_support.3.php

**Comment by ammarhakim** [comment]
This is now fixed. I have added a method to Mpi module `Mpi.Query_cuda_support()` that returns true if CUDA-aware MPI is present and false otherwise. We should put this test in the syncDevice() method to ensure that the code does not run on systems on which CUDA-aware MPI is not present.
