### ISSUE TITLE
Loop over species in the same order across MPI ranks for more robust IO

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkyl#39]
We have been looping over the species tables with loops like

for nm, s in pairs(species) do
   ...
end

`pairs` is the correct iterator for a table of name-value pairs. However, it is not deterministic: there is no guarantee that consecutive runs will loop in the same order. More importantly, there's no guarantee that different MPI ranks will loop in the same order. This is a problem for I/O (and possibly other operations), as one rank may be trying to output the ``ion`` distribution function at the same time as another rank may be outputting the ``electron`` distribution function.

I can conceive of 3 options for fixing this:

``A)`` Create a list of sorted keys, which we can store in the species table:
```
local species_keys = {}
for k in pairs(species) do table.insert(species_keys, k) end
table.sort(species_keys)
species["keys"] = lume.clone(species_keys)
```

then we can loop like
```
for i = 1, #species["keys"] do
   local nm, s = species["keys"][i], species[species["keys"][i]]
   ...
end
```

``B)`` Store the `key` table as the metadata table of species. First create `species_keys` as in option A above. Then
```
setmetatable(species,species_keys)
```

then loop like
```
for _, nm in ipairs(getmetatable(species)) do
   local s = species[nm]
   ...
end
```

``C)`` Create a centrally located iterator. For example we could create the `speciesIter` iterator and place it in gky/Lib, so that we would simply loop with

```
local speciesIter = require "Lib.speciesIter"

for nm, s in speciesIter(species) do
   ...
end
```

Option A has been implemented in branch newSpeciesLoops, commit 6ec2195. I'm waiting to merge to get input from others. The more I think about it, I'm not a fan of option C and if we are not going to use the metatable property of `species` for anything else, I'd vote for option B.

**Comment by nmandell** [comment]
Why does the order of species loops matter?

**Comment by manauref** [comment]
This came up as I was trying to do parallel simulations on my laptop (Mac + luajit-2.1.0-beta3-openresty + openmpi 4.0.5). With Regression/gk-neutrals/rt-neutrals-1x2vSOL.lua for example I would get errors like

`ERROR: Error when merging variable index lists. Variable in two different groups have the same path+name. Groups: elc and ion, variable: path=, name=time. Index aborted`

This doesn't always happen. I could run it a bunch of times and this would happen sometimes.

Jimmy reports that he and Tess where seeing similar errors elsewhere, and that they managed to mitigate it by downgrading luajit. The changes described in the above issue appeared to solve the error on my Mac, but not yet sure if it'll also solve it in the machines Jimmy+Tess were using.

In any case, unless Adios is very flexible, intuition tells me we shouldn't be writing different files with the same variable names from different ranks at the same time.

**Comment by manauref** [comment]
I should also add that not all species loops need to follow this pattern, as certain operations can be order-agnostic (e.g. charge density accumulation).

In those cases we may want to continue using a simple `pairs(species)` loop. However, in order to support such looping we can't use option ``A)`` above. Only options ``B)`` and ``C)`` could be made compatible with `pairs(species)`.

**Comment by manauref** [comment]
This has been solved in branch newSpeciesLoops with commits 

6ec2195cd7abb0b1b798f601c6e9666d6bb1d46d
bfa46540459fa4222bd75af20d84946f23a4d9d8

Jimmy tested on Frontera too and saw that an earlier similar errors went away with these changes.
