### ISSUE TITLE
Run unit tests as part of nightly regression testing

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/gkyl#5]
I have cleaned up the rununit command of the runregression Tool. To use this do:

`gkyl runregression rununit`

From the Regression directory.

Please add this to the nightly regression system. To do this do:

```
gkyl runregression rununit > outUnit
cat outUnit | grep FAILED!
cat outUnit | grep FAILED! | wc -l
```

Which will run the unit tests,  list the failed unit tests and count the number of failed tests. Please add this information to the nightly regression emails.

**Comment by pcagas** [comment]
The feature has been added. It should appear in the report tomorrow morning (11/21/2019)
