### ISSUE TITLE
receiving ERROR: Attribute element changeset has invalid value attribute

### ISSUE THREAD

**Issue by miketsukuba** [ammarhakim/gkyl#56]
Dear All,

Thanks for providing the code to the public.
I received error as (after first running the code):

(base) [usr@localhost vm-damp]$ gkyl vm-damp.lua
Tue Apr 27 2021 10:49:46.000000000
Gkyl built with 
Gkyl built on Apr 24 2021 18:42:00
Initializing Vlasov-Maxwell simulation ...
 ** WARNING: timeStepper not specified, assuming rk3
ERROR: Attribute element changeset has invalid value attribute
ERROR: Attribute element changeset has invalid value attribute
[localhost:04570] *** Process received signal ***
[localhost:04570] Signal: Segmentation fault (11)
[localhost:04570] Signal code: Address not mapped (1)
[localhost:04570] Failing at address: 0xfffffff7
[localhost:04570] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7f0a7c6c0370]
[localhost:04570] [ 1] /lib64/libc.so.6(cfree+0x1c)[0x7f0a7b3a638c]
[localhost:04570] [ 2] gkyl(adios_common_define_attribute_byvalue+0x3ce)[0x42f248]
[localhost:04570] [ 3] gkyl(adios_define_attribute_byvalue+0x50)[0x4290be]

I would be thankful to help me to correct run the first example.

All The Best

**Comment by JunoRavin** [comment]
Can you please post the full input file? Also it appears that at the start of the simulation the code is failing to get the git changeset you built. If you are running on a cluster/compute node, you should make sure that you have git so that the simulation can tell you what changeset of gkyl you are running.

**Comment by JunoRavin** [comment]
Could you also clarify how you built gkyl? Did you build from source or use the conda installation?

**Comment by miketsukuba** [comment]
Dear @JunoRavin, 
Many thanks for your comments,
Attached please find the input file.
for the building I used from source:
(but I did not use git, I just unzipped the downloaded version from the github.)
./machines/mkdeps.linux.sh
./machines/configure.linux.sh
./waf build install
(and then postgkyl with conda.)
conda config --add channels gkyl
conda install postgkyl
conda update -c gkyl postgkyl

All The Best
[vm-damp.lua.txt](https://github.com/ammarhakim/gkyl/files/6384537/vm-damp.lua.txt)

**Comment by nmandell** [comment]
Hi @miketsukuba,

Can you please re-download the zip file and try again? I just pushed a fix that I hope will solve your issue.

Thanks,
Noah

**Comment by miketsukuba** [comment]
Hi @nmandell,

Many thanks for the help. I will try again.

Kind Regards

**Comment by nmandell** [comment]
Actually need to make one more change, give me a minute

**Comment by nmandell** [comment]
Ok @miketsukuba, please try now. Thanks!

**Comment by miketsukuba** [comment]
Dear @nmandell and @JunoRavin,

Many thanks for your helps.
Sorry for being late.
Now it is working OK.

All The Best
