### ISSUE TITLE
--disable_cuda by default

### ISSUE THREAD

**Issue by sigvaldm** [ammarhakim/gkyl#57]
Dear Gkeyll team, first of all, thanks for making this software.

I am trying to build gkyl on a new cluster, but get the following eight errors (and many warnings, of which I show three) when running `waf` (in verbose mode):

```bash
[1203/1308] Compiling Eq/vlasovData/VlasovStreamMax1x2vP2.cpp
12:18:32 runner ['/cluster/software/CUDAcore/11.1.1/bin/nvcc', '-x', 'cu', '-c', '-dc', '-O3', '-std=c++14', '-lineinfo', '--maxrregcount=255', '-arch=sm_70', '--compiler-options="-fPIC"', '-IEq', '-I../Eq', '-ICuda', '-I../Cuda', '-IGrid', '-I../Grid', '-ILib', '-I../Lib', '-IBasis', '-I../Basis', '-IEq', '-I../Eq', '-IDataStruct', '-I../DataStruct', '-IEq/vlasovData', '-I../Eq/vlasovData', '-IEq/maxwellData', '-I../Eq/maxwellData', '../Eq/vlasovData/VlasovStreamMax1x2vP2.cpp', '-o', '/cluster/projects/nn9299k/software/gkyl-2.0_source/build/Eq/vlasovData/VlasovStreamMax1x2vP2.cpp.2.o']
../Eq/vlasovData/VlasovTmplModDecl.h(564): error: identifier "VlasovVolStream3x3vMaxP2" is undefined

../Eq/vlasovData/VlasovTmplModDecl.h(574): error: identifier "VlasovSurfStream3x3vMax_X_P2" is undefined

../Eq/vlasovData/VlasovTmplModDecl.h(577): error: identifier "VlasovSurfStream3x3vMax_Y_P2" is undefined

../Eq/vlasovData/VlasovTmplModDecl.h(580): error: identifier "VlasovSurfStream3x3vMax_Z_P2" is undefined

../Eq/vlasovData/VlasovTmplModDecl.h(586): error: identifier "VlasovVol3x3vMaxP2" is undefined

../Eq/vlasovData/VlasovTmplModDecl.h(597): error: identifier "VlasovSurfElcMag3x3vMax_VX_P2" is undefined

../Eq/vlasovData/VlasovTmplModDecl.h(600): error: identifier "VlasovSurfElcMag3x3vMax_VY_P2" is undefined

../Eq/vlasovData/VlasovTmplModDecl.h(603): error: identifier "VlasovSurfElcMag3x3vMax_VZ_P2" is undefined

8 errors detected in the compilation of "../Eq/vlasovData/VlasovTmplModDeviceFuncs.cpp".

../Eq/vlasovData/VlasovSurfElcMagMax3x3vP1.cpp(14): warning: variable "dv1" was declared but never referenced

../Eq/vlasovData/VlasovSurfElcMagMax3x3vP1.cpp(14): warning: variable "wv1" was declared but never referenced

../Eq/vlasovData/VlasovSurfElcMagMax3x3vP1.cpp(17): warning: variable "B0" was declared but never referenced
```
gkyl worked well on my laptop not long ago so I realize I'm probably doing something wrong. Do you have any idea what might cause these errors, or how I can go about debugging it?

For reference, I'm using commit `9267eeff17dee3be03f80816d1ad7c2004ed7f12`. I should also mention that I have changed the name of the `gkylsoft` folder in the machine files to better match the naming convention our group uses on the cluster.

Thank you.

**Comment by nmandell** [comment]
Hi Sigvald,

Can you please post your configure.* machine file? It looks like it has found NVCC on your system so it is trying to build with CUDA, but this is not fully supported right now. You can disable cuda by adding —disable-cuda to the waf command near the bottom of your configure machine file. 

@Gkeyll team I think —enable-cuda should default to false for now to prevent these kinds of issues. We just need to modify the machine files that do have CUDA support to add the —enable-cuda flag. I will do this today. 

Noah

**Comment by sigvaldm** [comment]
Thank you, this solved my issue. I did not realize that CUDA was not fully supported so I intentionally enabled it in the machine files. It is not important for me, however, and disabling it did the trick.

I changed the title of the issue and will leave it open so you can address the `--disable_cuda` thing nevertheless.
