### ISSUE TITLE
Five-Moment Two Fluid Vacuum Boundary Condition Riemann Solver

### ISSUE THREAD

**Issue by bezmi** [ammarhakim/gkyl#8]
Hi @pcagas, I'm currently working on implementing a plasma sheath model in a five moment multi-fluid code. In [this paper](https://arxiv.org/pdf/1610.06529.pdf) and your [dissertation](https://arxiv.org/pdf/1809.06368.pdf), a vacuum boundary condition is imposed in the ghost cells for the two-fluid model. Could you please point me towards which Riemann Solver is used for these boundary conditions?

**Comment by ammarhakim** [comment]
Hi @bezmi we typically use a Roe based Reimann solver to implement the boundary conditions. You can use an exact solver too, but it is usually not worth the extra effort. The results are nearly the same in either case. So I recommend using Roe solver.

**Comment by bezmi** [comment]
Great, thank you. Are the inputs files for the continuum kinetic and 5 moment sheath simulations available? It would be useful in validating our model, especially against the kinetic solver.
